import {defineField, defineType} from 'sanity'

const africanCountries = [
  {title: 'Algeria', value: 'Algeria'},
  {title: 'Angola', value: 'Angola'},
  {title: 'Benin', value: 'Benin'},
  {title: 'Botswana', value: 'Botswana'},
  {title: 'Burkina Faso', value: 'Burkina Faso'},
  {title: 'Burundi', value: 'Burundi'},
  {title: 'Cabo Verde', value: 'Cabo Verde'},
  {title: 'Cameroon', value: 'Cameroon'},
  {title: 'Central African Republic', value: 'Central African Republic'},
  {title: 'Chad', value: 'Chad'},
  {title: 'Comoros', value: 'Comoros'},
  {title: 'Congo', value: 'Congo'},
  {title: 'Democratic Republic of the Congo', value: 'Democratic Republic of the Congo'},
  {title: 'Djibouti', value: 'Djibouti'},
  {title: 'Egypt', value: 'Egypt'},
  {title: 'Equatorial Guinea', value: 'Equatorial Guinea'},
  {title: 'Eritrea', value: 'Eritrea'},
  {title: 'Eswatini', value: 'Eswatini'},
  {title: 'Ethiopia', value: 'Ethiopia'},
  {title: 'Gabon', value: 'Gabon'},
  {title: 'Gambia', value: 'Gambia'},
  {title: 'Ghana', value: 'Ghana'},
  {title: 'Guinea', value: 'Guinea'},
  {title: 'Guinea-Bissau', value: 'Guinea-Bissau'},
  {title: 'Ivory Coast', value: 'Ivory Coast'},
  {title: 'Kenya', value: 'Kenya'},
  {title: 'Lesotho', value: 'Lesotho'},
  {title: 'Liberia', value: 'Liberia'},
  {title: 'Libya', value: 'Libya'},
  {title: 'Madagascar', value: 'Madagascar'},
  {title: 'Malawi', value: 'Malawi'},
  {title: 'Mali', value: 'Mali'},
  {title: 'Mauritania', value: 'Mauritania'},
  {title: 'Mauritius', value: 'Mauritius'},
  {title: 'Morocco', value: 'Morocco'},
  {title: 'Mozambique', value: 'Mozambique'},
  {title: 'Namibia', value: 'Namibia'},
  {title: 'Niger', value: 'Niger'},
  {title: 'Nigeria', value: 'Nigeria'},
  {title: 'Rwanda', value: 'Rwanda'},
  {title: 'Sao Tome and Principe', value: 'Sao Tome and Principe'},
  {title: 'Senegal', value: 'Senegal'},
  {title: 'Seychelles', value: 'Seychelles'},
  {title: 'Sierra Leone', value: 'Sierra Leone'},
  {title: 'Somalia', value: 'Somalia'},
  {title: 'South Africa', value: 'South Africa'},
  {title: 'South Sudan', value: 'South Sudan'},
  {title: 'Sudan', value: 'Sudan'},
  {title: 'Tanzania', value: 'Tanzania'},
  {title: 'Togo', value: 'Togo'},
  {title: 'Tunisia', value: 'Tunisia'},
  {title: 'Uganda', value: 'Uganda'},
  {title: 'Zambia', value: 'Zambia'},
  {title: 'Zimbabwe', value: 'Zimbabwe'},
]

export default defineType({
  name: 'country',
  title: 'Country',
  type: 'document',
  fields: [
    defineField({
      name: 'name',
      title: 'Name',
      type: 'string',
      validation: (Rule) => Rule.required(),
      options: {
        list: africanCountries,
      },
    }),
    defineField({
      name: 'numMembers',
      title: 'Number of members',
      type: 'number',
      initialValue: 0,
      validation: (Rule) => [Rule.required(), Rule.min(0)],
    }),
    defineField({
      name: 'image',
      title: 'Image',
      type: 'image',
      options: {
        hotspot: true,
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'socials',
      title: 'Socials',
      type: 'array',
      of: [
        {
          type: 'object',
          fields: [
            {
              name: 'platform',
              title: 'Platform',
              type: 'string',
              validation: (Rule) => Rule.required(),
            },
            {
              name: 'handle',
              title: 'Handle',
              type: 'string',
              validation: (Rule) => [Rule.required(), Rule.regex(/^(http|https):\/\/[^ "]+$/)],
            },
          ],
        },
      ],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'publishedAt',
      title: 'Published at',
      type: 'datetime',
      initialValue: () => new Date().toISOString(),
      readOnly: true,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'author',
      title: 'Author',
      type: 'reference',
      to: {type: 'author'},
      validation: (Rule) => Rule.required(),
    }),
  ],

  preview: {
    select: {
      title: 'name',
      author: 'author.name',
      media: 'image',
    },
  },
})
